export enum AuditLogAction {
  // Tasks
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_DELETED = "TASK_DELETED",
  TASK_COMMENT_ADDED = "TASK_COMMENT_ADDED",
  TASK_COMMENT_UPDATED = "TASK_COMMENT_UPDATED",
  TASK_COMMENT_DELETED = "TASK_COMMENT_DELETED",
  TASK_ATTACHMENT_ADDED = "TASK_ATTACHMENT_ADDED",
  TASK_ATTACHMENT_REMOVED = "TASK_ATTACHMENT_REMOVED",

  // Projects
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
  PROJECT_ARCHIVED = "PROJECT_ARCHIVED",
  PROJECT_DELETED = "PROJECT_DELETED",
  PROJECT_MEMBERS_ASSIGNED = "PROJECT_MEMBERS_ASSIGNED",
  PROJECT_MEMBER_REMOVED = "PROJECT_MEMBER_REMOVED",

  // Invoices
  INVOICE_CREATED = "INVOICE_CREATED",
  INVOICE_UPDATED = "INVOICE_UPDATED",
  INVOICE_SENT = "INVOICE_SENT",
  INVOICE_PAID = "INVOICE_PAID",
  INVOICE_CANCELED = "INVOICE_CANCELED",
  INVOICE_DELETED = "INVOICE_DELETED",

  // Invitations
  INVITATION_SENT = "INVITATION_SENT",
  INVITATION_ACCEPTED = "INVITATION_ACCEPTED",
  INVITATION_REVOKED = "INVITATION_REVOKED",
  INVITATION_DECLINED = "INVITATION_DECLINED",

  // Member-related actions
  MEMBER_ROLE_UPDATED = "MEMBER_ROLE_UPDATED",
  MEMBER_DEACTIVATED = "MEMBER_DEACTIVATED",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  MEMBER_LEFT = "MEMBER_LEFT",
  MEMBER_OWNERSHIP_TRANSFERRED = "MEMBER_OWNERSHIP_TRANSFERRED",

  // Workspace / Team
  MEMBER_STATUS_UPDATED = "MEMBER_STATUS_UPDATED",

  // Workspace Lifecycle
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  WORKSPACE_UPDATED = "WORKSPACE_UPDATED",
  WORKSPACE_DELETED = "WORKSPACE_DELETED",
  WORKSPACE_ARCHIVED = "WORKSPACE_ARCHIVED",
  OWNERSHIP_TRANSFERRED = "OWNERSHIP_TRANSFERRED"
}

export enum AuditLogEntityType {
  TASK = "TASK",
  PROJECT = "PROJECT",
  INVOICE = "INVOICE",
  INVITATION = "INVITATION",
  USER = "USER",
  WORKSPACE = "WORKSPACE"
}
